@startuml
left to right direction
actor "Socio" as S1
:Bibliotecario:
rectangle Biblioteca{
usecase (reservar libro)
(prestar libro)
(devolver libro)
(actualizar código)
}
 S1-- (reservar libro)
 S1-- (prestar libro)
 S1-- (devolver libro)
:Bibliotecario: -- (reservar libro)
Bibliotecario -- (actualizar código)
@enduml

@startuml
left to right direction
"agente"
(evaluar\nSolicitud de credito)
(solicitar info adicional\nal cliente)
"agente" ..>(evaluar\nSolicitud de credito)
(solicitar info adicional\nal cliente)..>(evaluar\nSolicitud de credito):<<extend>>
@enduml
@startuml
left to right direction
Bibliotecario -->(baja socio)
(baja socio) ..> (buscar socio):<<include>>
@enduml